config/routes.rb
Rails.application.routes.draw do
  resources :websites
  match "/delayed_job" => DelayedJobWeb, :anchor => false, :via => [:get, :post]
  get 'admin' => 'admin#index'
  resources :batchs, only: [:index, :create]
  resources :diags, only: [:index, :create, :show], path: ''
  patch '/:id' => 'diags#create'
  root to: 'diags#index'
end

app/views/admin/index.html.erb
<%= content_for :title, 'Admin' %>
<%= javascript_include_tag 'application' %>
<main aria-label="Content" class="index">
  <header>
    <h1>
      <%= @diags.total_count %> diags
    </h1>
  </header>
  <section style="display:block">
    <%= area_chart Diag.group_by_day(:created_at, last: 30).count %>
  </section>
  <section>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">URL</th>
          <th scope="col">Status</th>
          <th scope="col">Date</th>
          <th scope="col">Views</th>
          <th scope="col">Website Carbon</th>
          <th scope="col">Weight</th>
          <th scope="col">CO2</th>
        </tr>
      </thead>
      <tbody>
        <% @diags.each do |diag| %>
          <tr>
            <th scope="row"><%= link_to diag.url.truncate(50), diag_path(diag, quiet: true) %></th>
            <td><%= diag.status %></td>
            <td><%= l diag.created_at.to_date %></td>
            <td><%= diag.views %></td>
            <td><%= diag.websitecarbon_score %></td>
            <td><%= number_to_human_size diag.total_byte_weight %></td>
            <td><%= diag.co2.round 2 %> g</td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @diags %>
  </section>
</main>